version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '03:00'
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(deps)
    groups:
      npm-minor-and-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: '03:30'
      timezone: Asia/Karachi
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore(ci)
